#在Spring Boot中多环境配置文件名需要满足application-{profile}.yml的格式，其中{profile}对应你的环境标识，比如：
#
#application-local.yml：开发环境
#application-test.yml：测试环境
#application-prod.yml：生产环境

spring:
  profiles:
    active: local
